DROP TABLE IF EXISTS prayers;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
   id SERIAL PRIMARY KEY,
   name TEXT NOT NULL,
   username VARCHAR(15) UNIQUE NOT NULL,
   password VARCHAR(100) NOT NULL
);

CREATE TABLE prayers (
   id SERIAL PRIMARY KEY,
   users_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
   prayer TEXT NOT NULL
);